export const dynamicRegistry = new Map<string, string[]>([
	[
		'core',
		[
			'core/blockWrapperUi',
			'core/toolBarUi',
			'icons/plusIcon',
			'icons/closeIcon',
			'icons/menuIcon',
			'extra/menu',
			'extra/dialog',
			'icons/deleteIcon',
			'icons/upIcon',
			'icons/downIcon'
		]
	],
	['paragraph', ['viewBlocks/viewParagraph', 'extra/textArea', 'icons/paragraphIcon']],
	['header', ['viewBlocks/viewHeader', 'icons/headerIcon', 'extra/select', 'extra/textArea']],
	[
		'image',
		['viewBlocks/viewImage', 'extra/upload', 'extra/input', 'icons/uploadIcon', 'icons/imageIcon']
	],
	[
		'list',
		[
			'viewBlocks/viewList',
			'extra/listHandler',
			'extra/textArea',
			'icons/plusIcon',
			'icons/closeIcon',
			'extra/select',
			'icons/listIcon'
		]
	],
	[
		'quote',
		[
			'viewBlocks/viewQuote',
			'icons/closeQuoteIcon',
			'icons/openQuoteIcon',
			'extra/input',
			'extra/textArea'
		]
	],
	['space', ['viewBlocks/viewSpace', 'extra/input', 'icons/spaceIcon']],
	[
		'code',
		[
			'viewBlocks/viewCode',
			'icons/copyIcon',
			'icons/doneIcon',
			'icons/codeIcon',
			'extra/select',
			'extra/textArea'
		]
	],
	[
		'checklist',
		[
			'viewBlocks/viewChecklist',
			'extra/checklistHandler',
			'icons/closeIcon',
			'icons/plusIcon',
			'extra/textArea',
			'icons/unCheckedIcon',
			'icons/checkedIcon',
			'icons/checklistIcon'
		]
	],
	[
		'embed',
		['viewBlocks/viewEmbed', 'icons/embedIcon', 'extra/description', 'extra/input', 'extra/loading']
	],
	[
		'attachment',
		[
			'viewBlocks/viewAttachment',
			'icons/attachmentIcon',
			'icons/uploadIcon',
			'extra/input',
			'extra/upload'
		]
	]
]);
